In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/ai4i2020.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [3]:
print(df.shape)

df.info()

(10000, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [4]:
df["temp_difference"] = (
    df["Process temperature [K]"]
    - df["Air temperature [K]"]
)

In [5]:
df["Type"] = df["Type"].map({
    "L": 0,
    "M": 1,
    "H": 2
})

In [6]:
df = df.drop(
    ["UDI", "Product ID"],
    axis=1
)

In [7]:
df["power_proxy"] = (
    df["Rotational speed [rpm]"]
    * df["Torque [Nm]"]
)

In [8]:
df["wear_torque_ratio"] = (
    df["Tool wear [min]"]
    /
    (df["Torque [Nm]"] + 1)
)

In [9]:
df["temp_stress_index"] = (
    df["temp_difference"]
    * df["Torque [Nm]"]
)

In [10]:
df["rpm_torque_interaction"] = (
    df["Rotational speed [rpm]"]
    * df["Torque [Nm]"]
)

In [11]:
df["wear_category"] = pd.cut(
    df["Tool wear [min]"],
    bins=[0,50,150,300],
    labels=["Low","Medium","High"]
)

In [12]:
df["wear_category"] = (
    df["wear_category"]
    .cat.codes
)

In [13]:
new_features = [
    "power_proxy",
    "wear_torque_ratio",
    "temp_stress_index",
    "rpm_torque_interaction",
    "wear_category"
]

df[new_features].head()

,power_proxy,wear_torque_ratio,temp_stress_index,rpm_torque_interaction,wear_category
0,66382.8,0.000000,449.40,66382.8,-1
1,65190.4,0.063425,486.15,65190.4,0
2,74001.2,0.099206,513.76,74001.2,0
3,56603.5,0.172840,410.80,56603.5,0
4,56320.0,0.219512,420.00,56320.0,0

In [14]:
corr = df.corr(numeric_only=True)

corr["Machine failure"]\
.sort_values(ascending=False)

Machine failure            1.000000
HDF                        0.575800
OSF                        0.531083
PWF                        0.522812
TWF                        0.362904
Torque [Nm]                0.191321
power_proxy                0.176039
rpm_torque_interaction     0.176039
temp_stress_index          0.123419
Tool wear [min]            0.105448
Air temperature [K]        0.082556
wear_category              0.080991
wear_torque_ratio          0.068416
Process temperature [K]    0.035946
RNF                        0.004516
Type                      -0.036715
Rotational speed [rpm]    -0.044188
temp_difference           -0.111676
Name: Machine failure, dtype: float64

In [15]:
df[new_features].describe()

,power_proxy,wear_torque_ratio,temp_stress_index,rpm_torque_interaction,wear_category
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,59967.147040,2.832776,399.961047,59967.147040,1.052200
std,10193.093881,2.001622,107.725221,10193.093881,0.759429
min,10966.800000,0.000000,36.860000,10966.800000,-1.000000
25%,53105.400000,1.297960,325.360000,53105.400000,1.000000
50%,59883.900000,2.606000,398.820000,59883.900000,1.000000
75%,66873.750000,4.036758,470.455000,66873.750000,2.000000
max,99980.400000,32.272727,857.920000,99980.400000,2.000000

In [16]:
df.to_csv(
    "/content/feature_engineered_ai4i.csv",
    index=False
)

print("Feature engineered dataset saved.")

Feature engineered dataset saved.

Week 1 Day 4 Summary

Implemented advanced predictive maintenance feature engineering.

Created:

• Power Consumption Proxy
• Wear-Torque Ratio
• Temperature Stress Index
• RPM-Torque Interaction
• Tool Wear Categories

These features capture machine operational stress, thermal behaviour and wear conditions, improving predictive maintenance modelling readiness.